version: '3.8'

services:
  db:
    container_name: gatekeeper_db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: gatekeeperdb
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gatekeeper-net

volumes:
  pgdata:

networks:
  gatekeeper-net:
    driver: bridge
